CREATE TABLE IF NOT EXISTS CUSTOMER(
  ID INT NOT NULL AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  TAX_ID VARCHAR(20) NOT NULL,
  BIRTHDAY DATE
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS ACCOUNT(
  ID INT NOT NULL AUTO_INCREMENT NOT NULL PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  NUMBER VARCHAR(20) UNIQUE NOT NULL,
  BALANCE DECIMAL(15, 2) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS TRANSFER(
  ID INT NOT NULL AUTO_INCREMENT NOT NULL PRIMARY KEY,
  ORIGIN_CUSTOMER_ID INT NOT NULL,
  DESTINY_CUSTOMER_ID INT NOT NULL,
  ORIGIN_ACCOUNT_ID INT NOT NULL,
  DESTINY_ACCOUNT_ID INT NOT NULL,
  TRANSFER_DATETIME DATETIME NOT NULL,
  AMOUNT DECIMAL(15, 2) NOT NULL,
  REGISTER_DATETIME DATETIME,
  FOREIGN KEY (ORIGIN_CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (DESTINY_CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (ORIGIN_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  FOREIGN KEY (DESTINY_ACCOUNT_ID) REFERENCES ACCOUNT(ID)
) ENGINE = INNODB;

INSERT INTO CUSTOMER (NAME, TAX_ID, BIRTHDAY) VALUES
('Gabriel Passos', '05227725950', '1997-04-21'),
('Thomas Soares', '94715088789', '1995-11-30');

INSERT INTO ACCOUNT (CUSTOMER_ID, NUMBER, BALANCE) VALUES
(1, '581768', 100),
(2, '792324', 150.30);
