CREATE TABLE IF NOT EXISTS ACCOUNT(
  ID INT NOT NULL AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NUMBER VARCHAR(20) UNIQUE NOT NULL,
  AMOUNT DECIMAL(15, 2) NOT NULL
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS CUSTOMER(
  ID INT NOT NULL AUTO_INCREMENT NOT NULL PRIMARY KEY,
  ACCOUNT_ID INT NOT NULL,
  TAX_ID VARCHAR(20) NOT NULL,
  BIRTHDAY DATE,
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS TRANSFER(
  ID INT NOT NULL AUTO_INCREMENT NOT NULL PRIMARY KEY,
  ORIGIN_CUSTOMER_ID INT NOT NULL,
  DESTINY_CUSTOMER_ID INT NOT NULL,
  ORIGIN_ACCOUNT_ID INT NOT NULL,
  DESTINY_ACCOUNT_ID INT NOT NULL,
  REGISTER_DATETIME DATETIME,
  FOREIGN KEY (ORIGIN_CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (DESTINY_CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (ORIGIN_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  FOREIGN KEY (DESTINY_ACCOUNT_ID) REFERENCES ACCOUNT(ID)
) ENGINE = INNODB;
