version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: db
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    networks:
      tcc:
        ipv4_address: 10.5.0.2
  mq:
    image: rabbitmq:3.5.6-management
    expose:
        - "5672"
        - "15672"
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      tcc:
        ipv4_address: 10.5.0.3

networks:
  tcc:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16