version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BANK
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    networks:
      tcc:
        ipv4_address: 10.5.0.2
  mq:
    image: rabbitmq:3.5.6-management
    expose:
        - "5672"
        - "15672"
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      tcc:
        ipv4_address: 10.5.0.3
  # transfer-producer:
  #   container_name: transfer-producer
  #   depends_on:
  #     - mysql
  #     - mq
  #   build:
  #     context: ./transfer-producer/
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     tcc:
  #       ipv4_address: 10.5.0.4
  # transfer-consumer:
  #   container_name: transfer-consumer
  #   depends_on:
  #     - mysql
  #     - mq
  #   build:
  #     context: ./transfer-consumer/
  #   ports:
  #     - "9001:9001"
  #   networks:
  #     tcc:
  #       ipv4_address: 10.5.0.5

networks:
  tcc:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
